- name: Enable firewalld
  service: name=firewalld state=started enabled=yes
- firewalld:
    port: 22/tcp
    permanent: true
    state: enabled
    immediate: yes
- name: Add authorized key for root
  authorized_key:
    user: root
    key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDftZwLvh3prVYPxD01zBpehPA6NVlL+iDajlDR2PqzB3odo5gVrV+u6vTyw/TfFR70uOkzoLjxl6x7ZbwXpKBAXqD8ke8gIDOAL4wz8QSKtj1lcLiLOEW0ToKhlwHvlZnA0e/GATtCgt/2y4F+h+jG0VmO3Ae+8aayCOSPVHqKhXcdKt5Qa++/7SuUrTuBN6ApJNp7HmVbMGdSbrr4I1gxNDYONompBTwVvBswBy8ySA+BNaAnKUxsX5gJJCtNENcbtg44TMHufmn69XZeUajDtNGeOgeITAIWnuEiOY+3R70idXJZGSDRnZzs4sXYmP7k4PQq07sWuHqXVKUzYWI/ test'
    state: present
- name: Add authorized key for root
  authorized_key:
    user: root
    key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBLmuvcDB2kz8MWlo3PFC4p/VvDFnZHpLkc7pF+LdRbw7m76ugsZoBdq+IoqnIQz0QgImKd8tG8+sMRLRMgThttxziKlUHJUuWMPya6+bX6JSo2XjyEnrfSP+eq8RnMEGbFG74QKR4OE6cXtrFIGD4ejFvg98u4oCFtj4IHuBsiyqhIO0KPAKigWhY12IpvTNNw3nOk84C85h9Vx+L0dw8npYozqXOnEQZNrz8a3KIhoXtMFlQjxuzBjfwD+mYMHCZ/topWJH2o09OPRXgqKlMZPiFbY3PUeI5GLpCdp5Th5Z8utjqzuG3SIEYb3NoNa72kJ/usj+AQa0GIrEP+DNL dhill@otto'
    state: present
