all:
  vars:
    enable_ssl: true
    db_name: test_db
    db_table: test_table
    db_username: test_user
    db_password: test_password
    db_hostname: ssh2.davidchill.ca
    ssl_bind_ip: 158.69.192.170
    bind_ip: "{{ ssl_bind_ip }}"
    domain_name: test.davidchill.ca
  children:
    webservers:
      hosts:
        ssh1.davidchill.ca:
        ssh2.davidchill.ca:
    dbservers:
      hosts:
        ssh2.davidchill.ca:
    dnsservers:
      hosts:
        ssh1.davidchill.ca:
        ssh2.davidchill.ca:
        ssh3.davidchill.ca:
    mailservers:
      hosts:
        ssh1.davidchill.ca:
        ssh2.davidchill.ca:
        ssh3.davidchill.ca:
    imapservers:
      hosts:
        ssh1.davidchill.ca:
